import { Public_Sans as PublicSans } from 'next/font/google';

import { AppLayout } from '@/ui/common/components/layouts/AppLayout';
import { AppProvider } from '@/ui/common/providers/AppProvider';

const publicSans = PublicSans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={publicSans.className} suppressHydrationWarning>
        <AppProvider>
          <AppLayout>{children}</AppLayout>
        </AppProvider>
      </body>
    </html>
  );
}
