import { Public_Sans as PublicSans } from 'next/font/google';

import { AppProvider } from '@/core/shared/providers';
import { AppLayout } from '@/ui/components/layout';

import './global.css';

const publicSans = PublicSans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${publicSans.className}`}>
        <AppProvider>
          <AppLayout>{children}</AppLayout>
        </AppProvider>
      </body>
    </html>
  );
}
