#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Fixing before push in API...'

# Check Prettier Standards
yarn fix:format ||
(
    echo 'Format error: Fix your format issues running `yarn fix:format`';
    false;
)

# Check ESLint Standards
yarn check:lint ||
(
        echo 'Linter error: Fix your linter issues running `yarn fix:lint`'
        false; 
)

# Check tsconfig standards
yarn check:types ||
(
    echo 'Types error: Fix your types issues manually :P'
    false;
)

# Run tests api
yarn test:api ||
(
    echo 'Tests error: Fix your tests issues manually :P'
    false;
)

echo '✅✅✅✅ Success ✅✅✅✅'
echo ''

